language: node_js

node_js: "node"

sudo: false

jobs:
  include:
    - name: Test
      node_js:
        - "node"
      before_install:
        - npm install -g codecov
      script:
        - npm test
      after_success:
        - npm run coverage
        - codecov

    - name: Lint
      script:
        - npm run lint

    - stage: npm release
      if: tag IS present
      cache: {}
      before_install: skip
      install: skip
      script: skip
      after_success: true  # Don't skip: To trigger the deploy
      before_deploy:
        - npm run compile
      deploy:
        provider: npm
        skip_cleanup: true
        email: thinca+npm@gmail.com
        api_key:
          secure: H4a478LmEwjAQB/Rq0D0D7YqUEvBLRQ8FyzAM1XqBmTZojUCeudZPIE97gVGR/JwUKiRVPubuoEyRw+1nGZpnsfDS7wz+orhjbme+Ksk6DoxQqDBzk/TzRCZ3A2oZOtUcMDMm5sPVatinCtQ/0AynwkDhPdD8d+WZjar6pfO5gYn2M6gVt8bbm3p8VXzQjzDp2J/1AVm2R5ipAyd7kLpMVseUEueTClNi9bLy+xBRgbbB9BmhwR0skwhwl73/Af++QnI4vgUCVNmXId8SQzOHv9Glxgnv8OGK9KpRnrB+7b8dMZnhZLMfDMjkZ2SFNVTXLU8b8dZX16OPsKRB7WwZGo86+ewXUrZCJz+g39Vc40+udDUd/j7JC5G0zaxqKipENq3mlZvsmbbr/h3YaUp84F3jatTphYh6V98euGsdMWIepV416TW8N759qYWN0hwMEBdwWgn51I2Id86Sz8ssKbvRyTglfK3OtpW1ZGL8m27l8lhYrBVkSvdUXAoXcLtoRWfDQIhOfu0cRu686UT/oTinmgfWqbOpiaiBclE6JKN9OeVdwpqe4Lmv9e7X3JAwdBqUV7HLVAkwcWUOMkMG6ixo4VBXESHjANzAFNafxY1DfiZXr27ISE4+GRkGN5fPDhptgQJTPaewn7/6YgdUEvb1/bNFvbZTiBW6rgWKq4=
        on:
          tags: true
